export const GET_CONTENT = 'GET_CONTENT'
export const ADD_CONTENT = 'ADD_CONTENT'
export const UPDATE_CONTENT = 'UPDATE_CONTENT'
export const DELETE_CONTENT = 'DELETE_CONTENT'
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY'
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY'


export const SORT_BY_LAST_UPLOAD = 'SORT_BY_LAST_UPLOAD'
export const SORT_BY_FIRST_UPLOAD = 'SORT_BY_FIRST_UPLOAD'
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY'
export const CLEAR_ALL_FILTER = 'CLEAR_ALL_FILTER'

