export const LOAD_NEWS = 'LOAD_NEWS'
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY'
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY'


export const SORT_BY_LAST_UPLOAD = 'SORT_BY_LAST_UPLOAD'
export const SORT_BY_FIRST_UPLOAD = 'SORT_BY_FIRST_UPLOAD'
